services:
  postgres: 
    image: "postgres"
    restart: always
    environment:
      POSTGRES_PASSWORD: "password"
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata: 

