name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build-realtime-server:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/ring-server:latest

  notify-watchtower:
    needs: [build-website, build-worker]
    runs-on: ubuntu-latest
    steps:
      - name: Notify
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://watchtower.drewh.net/v1/update'
          preventFailureOnNoResponse: "true"
          method: 'GET'
          customHeaders: '{"Authorization": "Bearer ${{secrets.WATCHTOWER_KEY}}"}'
